# Variables à définir au niveau du projet Gitlab, avec l'option "masquée" :
# - AWS_ACCESS_KEY_ID_OPEN      : Identifiant AWS pour les environnements Open
# - AWS_SECRET_ACCESS_KEY_OPEN  : Clé AWS pour les environnements Open
# - AWS_ACCESS_KEY_ID_MC        : Identifiant AWS pour les environnements du Ministère de la Culture
# - AWS_SECRET_ACCESS_KEY_MC    : Clé AWS pour les environnements du Ministère de la Culture
#
default:
  image: node:14.17

include:
  - project: "boost/template-ci/pipelines/common"
    file: 
      - "sonar/sonar.yml"

stages:
  - node-modules
  - test
  - quality
#  - sast
#  - build
#  - deploy
#  - staging
#  - production

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'


##############################################################
# TEMPLATES
#

.install-awsebcli: &install-awsebcli
  - pip install awsebcli

.aws-open-credentials: &aws-open-credentials
  - mkdir ~/.aws
  - echo "[eb-cli]" > ~/.aws/credentials
  - echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_OPEN}" >> ~/.aws/credentials
  - echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_OPEN}" >> ~/.aws/credentials

.aws-mc-credentials: &aws-mc-credentials
  - mkdir ~/.aws
  - echo "[default]" > ~/.aws/credentials
  - echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_MC}" >> ~/.aws/credentials
  - echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_MC}" >> ~/.aws/credentials

# Variables à utiliser avec ce template :
#   - APP : Nom du module applicatif à compiler (api, diffusion, consultation).
#   - ENV : Nom de l'environnement AWS cible.
#   - NAME: Nom de l'application (présent dans le fichier .elasticbeanstalk/config.yml)
#   - REPLACE: Nom de l'application cible AWS
#
.deploy-open: &deploy-open
  stage: deploy
  image: python:3.9
  script:
    - *install-awsebcli
    - *aws-open-credentials
    - cd apps/${APP}
    - sed -i "s/${NAME}/${REPLACE}/" .elasticbeanstalk/config.yml
    - eb deploy ${ENV}

# Variables à utiliser avec ce template :
#   - APP : Nom du module applicatif à compiler (api, diffusion, consultation).
#   - ENV : Nom de l'environnement AWS cible.
#
.deploy-mc: &deploy-mc
  stage: deploy
  image: python:3.9
  script:
    - *install-awsebcli
    - *aws-mc-credentials
    - cd apps/${APP}
    - eb deploy ${ENV}

##############################################################
# NODE-MODULES
#
# Variables à utiliser avec ce template :
#   - APP : Nom du module applicatif à compiler (api, diffusion, consultation).
.node-modules: &node-modules
  stage: node-modules
  script:
    - cd apps/${APP}
    - npm ci
  artifacts:
    paths: 
      - apps/${APP}/node_modules
    name: ${APP}-modules
    expire_in: 1 hour

node-modules-api:
  <<: *node-modules
  variables:
    APP: api

node-modules-production:
  <<: *node-modules
  variables:
    APP: production

node-modules-diffusion:
  <<: *node-modules
  variables:
    APP: diffusion

##############################################################
# TEST
#
# Variables à utiliser avec ce template :
#   - APP : Nom du module applicatif à compiler (api, diffusion, consultation).
.test: &test
  stage: test
  script:
    - cd apps/${APP}
    - npm test
  artifacts:
    name: coverage-rapport
    expire_in: 1 hrs
    when: always
    paths:
      - apps/${APP}/coverage

test-api:
  needs:
    - node-modules-api
  <<: *test
  services:
    - mongo:4.4
  variables:
    APP: api
    DB_ENDPOINT: mongodb://mongo:27017/pop

test-production:
  needs:
    - node-modules-production
  <<: *test
  variables:
    APP: production

test-diffusion:
  needs:
    - node-modules-diffusion
  <<: *test
  variables:
    APP: diffusion

##############################################################
# SONAR
#
# Variables à utiliser avec ce template :
#   - APP : Nom du module applicatif à compiler (api, diffusion, consultation).
sonar-api:
extends: [".sonar"]
  variables:
    SONAR_BRANCH: "-Dsonar.branch.name=${BRANCH_NAME} -Dsonar.branch.target=${BRANCH_TARGET}"
    SONAR_PUBLISHER_OPTIONS: "-Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${REF_NAME} -Dsonar.gitlab.project_id=${CI_PROJECT_ID}.api"
  rules:
    - if: '$QUALITY_DISABLE == "true"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        BRANCH_NAME: $CI_COMMIT_REF_NAME
        BRANCH_TARGET: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        REF_NAME: $CI_MERGE_REQUEST_REF_PATH
    - if: '$CI_PIPELINE_SOURCE == "push"'
      variables:
        BRANCH_NAME: $CI_COMMIT_REF_NAME
        BRANCH_TARGET: $CI_DEFAULT_BRANCH
        REF_NAME: $CI_COMMIT_REF_NAME
