version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongo
#    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: pop
      # MONGO_INITDB_ROOT_USERNAME: userTest
      # MONGO_INITDB_ROOT_PASSWORD: userTestPasssord
    networks:
      - mongo_elasticsearch_network

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    ports:
      - "9200:9200"
    # volumes:
    #   - elasticsearch_data:/usr/share/elasticsearch/data
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - mongo_elasticsearch_network

  # For api test purpose 
  api:
    build:
      context: ./apps/api
    environment:
      ES_ENDPOINT: http://elasticsearch:9200
      DB_ENDPOINT: mongodb://mongodb:27017
    ports:
      - "3000:3000"
    networks:
      - mongo_elasticsearch_network

  # For production test purpose 
  production:
    build:
      context: ./apps/production
    environment:
      API_URL: http://api:3000
      POP_URL: http://api:3001
    ports:
      - "8080:8081"
    networks:
      - mongo_elasticsearch_network

networks:
  mongo_elasticsearch_network:
