environment-defaults:
  pop-api-staging:
    branch: null
    repository: null
global:
  application_name: pop-api
  branch: null
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-3::platform/Node.js 14 running on
    64bit Amazon Linux 2/5.4.9
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
